Add references to state
domnikl/schema-registry-gitops pull request #18
Opened 2022-02-10 11:34 UTC by smdawe

2022-02-10 11:52 UTC, smdawe commented
@domnikl I have this PR ready.

2022-02-11 15:13 UTC, domnikl requested changes
Big thank you for the PR @smdawe! A commented a few little things that need changes. Also this should be documented in the README, but I can also do that afterwards.

2022-02-11 15:13 UTC, domnikl commented on examples/schema-registry.yml
> +        subject: User
Subject is named `User-value` above.

2022-02-11 15:13 UTC, domnikl commented on examples/with-references.avsc
> +}
Please add a newline at end of file.

2022-02-11 17:01 UTC, smdawe commented
@domnikl thanks for your feedback.  All issues raised have been addressed.  This has been my first dip into kotlin and I have really enjoyed what I have seen so far.

2022-02-13 09:32 UTC, domnikl approved these changes
@smdawe looks good now! Glad you enjoyed your first dip into Kotlin 😄

2022-02-13 09:32 UTC, merged